Repository GibbonEdu/core, pull requests merged in 2021-11, with the labels that each got.

#1484 System: change gibbonSession table creation
  CHANGEDB.php
  gibbon.sql
Labels: bug, enhancement

#1492 Debug installer issue with database update
  gibbon.sql
  src/Database/Updater.php
Labels: bug

#1491 System: removed deprecated functions no longer used in core and additional modules
  CHANGELOG.txt
  functions.php
  modules/Attendance/attendance_take_byFormGroup.php
  modules/Finance/expenseRequest_manage_reimburse.php
  modules/Finance/expenseRequest_manage_view.php
  modules/Finance/expenses_manage_approve.php
  modules/Finance/expenses_manage_print.php
  modules/Finance/expenses_manage_print_print.php
  modules/Finance/expenses_manage_view.php
  modules/Form Groups/formGroups_details.php
  modules/Formal Assessment/externalAssessment_details.php
  modules/Individual Needs/in_edit.php
  modules/Markbook/markbook_view_myMarks.php
  modules/Markbook/markbook_view_viewMyChildrensClasses.php
  modules/Planner/outcomes.php
  modules/Staff/applicationForm_manage_edit_print.php
  modules/Students/applicationForm_manage_edit_print.php
  modules/Students/student_view_details.php
  modules/System Admin/moduleFunctions.php
  modules/System Admin/systemSettings.php
  modules/Timetable/tt_view.php
  src/UI/Dashboard/ParentDashboard.php
Labels: enhancement

#1490 System: fix Url class not returning an absolute URL
  index.php
  indexFindRedirect.php
  passwordResetProcess.php
  resources/templates/index.twig.html
  resources/templates/mail/email.twig.html
  src/Http/Url.php
  src/UI/Dashboard/StaffDashboard.php
  src/UI/Dashboard/StudentDashboard.php
  src/View/Components/Breadcrumbs.php
  tests/unit/Gibbon/UrlTest.php
Labels: bug

#1493 System: removed deprecated core functions from functions.php
  CHANGELOG.txt
  functions.php
  modules/Crowd Assessment/crowdAssess_view_discuss_postProcess.php
  modules/Finance/expenseApprovers_manage_addProcess.php
  modules/Finance/expenseRequest_manage_reimburseProcess.php
  modules/Finance/expenseRequest_manage_viewProcess.php
  modules/Finance/expenses_manage_approveProcess.php
  modules/Finance/expenses_manage_editProcess.php
  modules/Finance/moduleFunctions.php
  src/Domain/Students/StudentGateway.php
Labels: refactoring

#1494 System: update Chart.js library to v3.6.0 and migrate existing charts
  CHANGELOG.txt
  index.php
  lib/Chart.js/2.0/Chart.bundle.js
  lib/Chart.js/2.0/Chart.bundle.min.js
  lib/Chart.js/2.0/Chart.js
  lib/Chart.js/2.0/Chart.min.js
  lib/Chart.js/3.0/chart.js
  lib/Chart.js/3.0/chart.min.js
  lib/Chart.js/CONTRIBUTING.md
  lib/Chart.js/Chart.min.js
  lib/Chart.js/LICENSE.md
  lib/Chart.js/MAINTAINING.md
  lib/Chart.js/README.md
  lib/Chart.js/bower.json
  lib/Chart.js/gulpfile.js
  lib/Chart.js/package.json
  lib/Chart.js/src/Chart.Bar.js
  lib/Chart.js/src/Chart.Core.js
  lib/Chart.js/src/Chart.Doughnut.js
  lib/Chart.js/src/Chart.Line.js
  lib/Chart.js/src/Chart.PolarArea.js
  lib/Chart.js/src/Chart.Radar.js
  modules/Attendance/report_graph_byType.php
  modules/Attendance/src/StudentHistoryView.php
  modules/Individual Needs/report_graph_overview.php
  modules/Rubrics/src/Visualise.php
  modules/Staff/report_absences_weekly.php
  modules/Students/report_graph_studentEnrolment.php
  src/Tables/Prefab/EnrolmentTable.php
  src/UI/Chart/Chart.php
  tests/unit/UI/Chart/ChartTest.php
Labels: javascript, refactoring

#1561 Improve warning detection in test
  .github/workflows/ci.yml
Labels: testing, enhancement

#1570 Formal Assessment, Individual Needs - null coalesce in interface
  modules/Formal Assessment/externalAssessment_manage_details_add.php
  modules/Individual Needs/in_edit.php
  modules/Individual Needs/in_view.php
  modules/Individual Needs/report_graph_overview.php
Labels: refactoring

#1569 Finance - null coalesce refactoring in interface files
  modules/Finance/expenseRequest_manage_view.php
  modules/Finance/expenses_manage_approve.php
  modules/Finance/expenses_manage_edit.php
  modules/Finance/expenses_manage_print.php
  modules/Finance/expenses_manage_print_print.php
  modules/Finance/expenses_manage_view.php
  modules/Finance/fees_manage.php
  modules/Finance/invoices_manage.php
  modules/Finance/invoices_manage_add.php
  modules/Finance/invoices_manage_edit.php
  modules/Finance/invoices_manage_issue.php
Labels: refactoring

#1568 Data Updater - null coalesce refactoring in interface pages
  modules/Data Updater/data_family.php
  modules/Data Updater/data_family_manage.php
  modules/Data Updater/data_family_manage_edit.php
  modules/Data Updater/data_finance.php
  modules/Data Updater/data_finance_manage.php
  modules/Data Updater/data_finance_manage_edit.php
  modules/Data Updater/data_medical.php
  modules/Data Updater/data_medical_manage.php
  modules/Data Updater/data_medical_manage_edit.php
  modules/Data Updater/data_personal.php
  modules/Data Updater/data_personal_manage.php
  modules/Data Updater/data_personal_manage_edit.php
  modules/Data Updater/data_staff_manage.php
  modules/Data Updater/report_family_dataUpdaterHistory.php
  modules/Data Updater/report_student_dataUpdaterHistory.php
Labels: refactoring

#1567 Behaviour - null coalesce refactoring in interface pages
  modules/Behaviour/behaviour_letters.php
  modules/Behaviour/behaviour_manage.php
  modules/Behaviour/behaviour_manage_add.php
  modules/Behaviour/behaviour_pattern.php
  modules/Behaviour/behaviour_view.php
Labels: refactoring

#1566 Attendance - null coalesce refactoring in interface files
  modules/Attendance/attendance_take_byCourseClass.php
  modules/Attendance/attendance_take_byPerson.php
  modules/Attendance/attendance_take_byPerson_delete.php
  modules/Attendance/attendance_take_byPerson_edit.php
Labels: refactoring

#1565 Activities - null coalesce refactoring
  modules/Activities/activities_paymentProcessBulk.php
  modules/Activities/activities_view_register.php
  modules/Activities/report_activityEnrollmentSummary.php
  modules/Activities/report_activityType_formGroup.php
  modules/Activities/report_attendance_byDate.php
  modules/Activities/report_participants.php
Labels: refactoring
