Repository GibbonEdu/core, pull requests merged in 2021-08, with the labels that each got.

#1396 Update google/apiclient
  composer.json
  composer.lock
Labels: bug, dependencies

#1409 Fix Composer PSR-4 library warnings
  composer.json
  composer.lock
Labels: dependencies

#1410 System Admin: fix missing Custom Imports Folder setting
  CHANGEDB.php
  modules/System Admin/import_manage.php
  modules/System Admin/import_manageProcess.php
  src/Data/ImportType.php
Labels: new feature, php
