Repository GibbonEdu/core, pull requests merged in 2021-12, with the labels that each got.

#1574 Updated module name
  modules/.gitignore
Labels: refactoring

#1576 Fixed parameter (student_view_details instead of staff_view_details)
  src/Services/Format.php
Labels: bug

#1579 Added translation support for sortable attributes to the multi-select
  modules/System Admin/activeSessions.php
  src/Forms/Input/MultiSelect.php
Labels: bug

#1580 Component listOptions fixed
  resources/templates/components/listOptions.twig.html
  src/Tables/View/PaginatedView.php
Labels: bug

#1586 Added Libyan Currency
  src/Forms/FormFactory.php
Labels: enhancement

#1590 Sync students classes fix
  modules/Timetable Admin/courseEnrolment_sync_runProcess.php
Labels: enhancement

#1588 Timetable: Fixed calenders not persisting when timetable is changed
  modules/Timetable/moduleFunctions.php
Labels: bug

#1587 Reports: Added default value for Yes/No criteria type
  CHANGEDB.php
  CHANGELOG.txt
  gibbon.sql
  modules/Reports/criteriaTypes_manage_add.php
  modules/Reports/criteriaTypes_manage_addProcess.php
  modules/Reports/criteriaTypes_manage_edit.php
  modules/Reports/criteriaTypes_manage_editProcess.php
  modules/Reports/reporting_write_byStudent.php
  modules/Reports/src/Domain/ReportingAccessGateway.php
Labels: enhancement

#1572 Markbook - null coalesce in interface pages
  modules/Markbook/markbook_edit_add.php
Labels: refactoring

#1578 Identifying internal urls in the nameLinked function
  src/Services/Format.php
Labels: bug

#1571 Library - null coalesce in interface pages
  modules/Library/library_browse.php
  modules/Library/library_manage_catalog_fields_ajax.php
  modules/Library/library_manage_catalog_idCheckAjax.php
Labels: refactoring

#1573 Messenger - null coalesce in interface pages
  modules/Messenger/groups_manage_editProcess.php
  modules/Messenger/messenger_manage_delete.php
  modules/Messenger/messenger_manage_edit.php
  modules/Messenger/messenger_manage_report.php
Labels: refactoring

#1589 User Admin: User Status Log (WIP)
  CHANGEDB.php
  cli/userAdmin_statusCheckAndFix.php
  modules/Students/student_view_details.php
  modules/User Admin/user_manage_edit.php
  modules/User Admin/user_manage_editProcess.php
  modules/User Admin/user_manage_view_status_log.php
  src/Domain/User/UserStatusLogGateway.php
Labels: enhancement

#1592 School Admin: add an option to send Positive Behaviour Letters
  CHANGEDB.php
  cli/behaviour_lettersNegative.php
  cli/behaviour_lettersPositive.php
  modules/School Admin/behaviourSettings.php
  modules/School Admin/behaviourSettingsProcess.php
Labels: enhancement

#1593 School Admin: add option to configure activity types individually
  CHANGEDB.php
  modules/Activities/activities_manage_add.php
  modules/Activities/activities_manage_edit.php
  modules/Activities/activities_manage_enrolment.php
  modules/Activities/activities_manage_enrolment_add.php
  modules/Activities/activities_manage_enrolment_edit.php
  modules/Activities/activities_my.php
  modules/Activities/activities_my_full.php
  modules/Activities/activities_view.php
  modules/Activities/activities_view_full.php
  modules/Activities/activities_view_register.php
  modules/Activities/activities_view_registerProcess.php
  modules/Activities/report_activityChoices_byStudent.php
  modules/Activities/report_activityType_formGroup.php
  modules/School Admin/activitySettings.php
  modules/School Admin/activitySettingsProcess.php
  modules/School Admin/activitySettings_type_add.php
  modules/School Admin/activitySettings_type_addProcess.php
  modules/School Admin/activitySettings_type_delete.php
  modules/School Admin/activitySettings_type_deleteProcess.php
  modules/School Admin/activitySettings_type_edit.php
  modules/School Admin/activitySettings_type_editProcess.php
  src/Database/Migrations/2021-12-30-ActivityTypes.php
  src/Domain/Activities/ActivityGateway.php
  src/Domain/Activities/ActivityTypeGateway.php
  src/UI/Dashboard/ParentDashboard.php
  tests/acceptance/School Admin/ActivitySettingsCept.php
Labels: enhancement

#1591 System: final refactoring of legacy year selector code
  modules/Data Updater/data_family_manage.php
  modules/Data Updater/data_finance_manage.php
  modules/Data Updater/data_medical_manage.php
  modules/Data Updater/data_personal_manage.php
  modules/Data Updater/data_staff_manage.php
  modules/Finance/billingSchedule_manage.php
  modules/Finance/fees_manage.php
  modules/Finance/invoices_manage.php
  modules/Finance/invoices_view.php
  modules/Planner/units.php
  modules/Planner/units_public.php
  modules/Planner/units_public_view.php
  modules/Reports/archive_byReport.php
  modules/Reports/reports_manage.php
  modules/School Admin/formGroup_manage.php
  modules/School Admin/formGroup_manage_add.php
  modules/School Admin/formGroup_manage_edit.php
  modules/School Admin/schoolYearSpecialDay_manage.php
  modules/Staff/applicationForm_manage_accept.php
  modules/Students/studentEnrolment_manage.php
  modules/Timetable Admin/courseEnrolment_manage.php
  modules/Timetable Admin/courseEnrolment_manage_byPerson.php
  modules/Timetable Admin/courseEnrolment_manage_byPerson_edit.php
  modules/Timetable Admin/courseEnrolment_sync.php
  modules/Timetable Admin/course_manage.php
  modules/Timetable Admin/tt.php
  modules/Timetable Admin/ttDates.php
  resources/templates/page.twig.html
  src/View/Components/Navigator.php
Labels: refactoring

#1581 Alert levels review
  functions.php
  modules/Data Updater/data_medical_manage_editProcess.php
  modules/Students/medicalForm_manage_condition_editProcess.php
Labels: enhancement
