Repository GibbonEdu/core, pull requests merged in 2022-02, with the labels that each got.

#1603 Installer: fix homepage link generation
  installer/install.php
  tests/install/InstallCept.php
Labels: bug

#1605 System: improve logs for login process, fix login info in View Logs
  CHANGELOG.txt
  login.php
  src/Auth/Adapter/AuthenticationAdapter.php
  src/Auth/Adapter/OAuthGenericAdapter.php
  src/Auth/Adapter/OAuthGoogleAdapter.php
  src/Auth/Adapter/OAuthMicrosoftAdapter.php
Labels: bug, enhancement

#1606 System Admin: improve the reliability of the uploads folder check
  CHANGELOG.txt
  modules/System Admin/moduleFunctions.php
  modules/System Admin/systemCheck.php
  modules/System Admin/systemOverview.php
Labels: enhancement

#1608 System Admin: add an Upload Photos & Files page, replacing the old Import User Photos
  CHANGEDB.php
  CHANGELOG.txt
  modules/System Admin/css/module.css
  modules/System Admin/file_upload.php
  modules/System Admin/file_uploadPreview.php
  modules/System Admin/file_uploadProcess.php
  modules/User Admin/import_userPhotos.php
  src/Domain/System/CustomFieldGateway.php
  src/Domain/User/PersonalDocumentGateway.php
  src/Domain/User/PersonalDocumentTypeGateway.php
  src/Forms/Input/Range.php
  src/Gibbon/FileUploader.php
Labels: enhancement
