Repository GibbonEdu/core, pull requests merged in 2022-11, with the labels that each got.

#1694 Tests: streamline CI test environment
  .github/workflows/ci.yml
  .gitlab-ci.yml
  composer.json
  tests/_envs/.gitignore
  tests/_envs/env.yml
  tests/_envs/environment.php
  tests/_envs/gitlab_ci.yml
  tests/_envs/travis_ci.yml
  tests/acceptance.suite.yml
  tests/install.suite.yml
  tests/install/InstallCept.php
Labels: testing

#1693 Fix phpstan issues
  composer.lock
  src/Auth/Adapter/DefaultAdapter.php
  src/Auth/Adapter/MFAAdapter.php
  src/Database/Updater.php
  src/Forms/Builder/Fields/FieldGroupInterface.php
  src/Forms/Builder/Fields/RequiredDocuments.php
  src/Forms/Builder/FormBuilder.php
  src/Forms/Builder/Process/CreateStudent.php
  src/Forms/DatabaseFormFactory.php
  src/Forms/Form.php
  src/Gibbon/Core.php
  src/Install/Config.php
  src/Services/Payment/Payment.php
Labels: enhancement

#1690 Students: fix phpdocs for getHighestMedicalRisk
  functions.php
Labels: documentation

#1698 GitHub CI: Improve debug experience with twig
  .github/workflows/ci.yml
  .gitignore
Labels: testing

#1697 Services: improve FormatTest
  tests/unit/Services/FormatTest.php
Labels: testing

#1696 Deprecate nl2brr
  functions.php
  modules/Behaviour/behaviour_letters.php
  modules/Behaviour/behaviour_manage.php
  modules/Behaviour/moduleFunctions.php
  modules/Individual Needs/investigations_manage.php
  modules/Individual Needs/investigations_manage_edit.php
  modules/Students/firstAidRecord.php
  modules/Students/medicalForm_manage.php
Labels: refactoring

#1685 Refactor password policy
  functions.php
  modules/User Admin/user_manage_add.php
  modules/User Admin/user_manage_addProcess.php
  modules/User Admin/user_manage_password.php
  modules/User Admin/user_manage_passwordProcess.php
  passwordReset.php
  passwordResetProcess.php
  preferences.php
  preferencesPasswordProcess.php
  publicRegistration.php
  publicRegistrationProcess.php
  src/Data/PasswordPolicy.php
  src/Install/Http/InstallController.php
  src/Install/Installer.php
  src/Services/CoreServiceProvider.php
  tests/unit/Data/PasswordPolicyCest.php
Labels: refactoring

#1683 Services: replace emailBodyConvert calls with Format::emailBodyToPlain
  functions.php
  modules/Staff/applicationForm_manage_accept.php
  modules/Students/applicationForm_manage_accept.php
  src/Services/Format.php
Labels: refactoring

#1682 Replace getRoleCategory with gateway method
  functions.php
  index.php
  modules/Activities/activities_my_full.php
  modules/Activities/activities_view.php
  modules/Activities/activities_view_full.php
  modules/Activities/activities_view_register.php
  modules/Activities/activities_view_registerProcess.php
  modules/Crowd Assessment/moduleFunctions.php
  modules/Data Updater/data_personal.php
  modules/Data Updater/data_personalProcess.php
  modules/Data Updater/data_personal_manage_edit.php
  modules/Data Updater/data_personal_manage_editProcess.php
  modules/Form Groups/formGroups.php
  modules/Markbook/markbook_view_rubric.php
  modules/Messenger/src/Forms/MessageForm.php
  modules/Messenger/src/MessageTargets.php
  modules/Planner/planner_deadlines.php
  modules/Planner/planner_deadlinesAjax.php
  modules/Planner/planner_view_full.php
  modules/Reports/archive_byReport.php
  modules/Reports/archive_byReport_download.php
  modules/Reports/archive_byReport_view.php
  modules/Reports/archive_byStudent.php
  modules/Reports/archive_byStudent_download.php
  modules/Reports/archive_byStudent_view.php
  modules/Reports/reports_send.php
  modules/Reports/reports_send_batch.php
  modules/Rubrics/rubrics_view.php
  modules/Students/student_view_details.php
  modules/Timetable/moduleFunctions.php
  modules/Timetable/tt.php
  modules/Timetable/tt_view.php
  modules/User Admin/user_manage_edit.php
  modules/User Admin/user_manage_editProcess.php
  modules/User Admin/user_manage_userPhotoAjax.php
  preferences.php
  src/Domain/Messenger/MessengerGateway.php
  src/Domain/User/RoleGateway.php
  src/UI/Components/Sidebar.php
  src/UI/Dashboard/StaffDashboard.php
  src/UI/Dashboard/StudentDashboard.php
Labels: refactoring

#1701 Data: explicit type-cast in ImportType
  src/Data/ImportType.php
Labels: enhancement

#1650 Format: replace strftime with IntlDateFormatter
  composer.json
  modules/Finance/src/Forms/FinanceFormFactory.php
  modules/Formal Assessment/moduleFunctions.php
  modules/Timetable/moduleFunctions.php
  src/Services/Format.php
  version.php
Labels: refactoring

#1703 System: fix dateRangeReadable usage of IntlDateFormatter
  src/Services/Format.php
Labels: refactoring

#1700 System: deprecate randomPassword
  cli/schoolAdmin_parentWeeklyEmailSummary.php
  functions.php
  modules/Activities/activities_paymentProcessBulk.php
  modules/Finance/invoices_manage_addProcess.php
  modules/Messenger/src/MessageTargets.php
  modules/Staff/applicationForm_manage_accept.php
  modules/Students/applicationForm_manage_accept.php
  modules/System Admin/import_history.php
  modules/System Admin/import_manage.php
  passwordResetProcess.php
  src/Data/ImportType.php
  src/Data/PasswordPolicy.php
  src/Forms/Builder/Process/CreateParents.php
  src/Forms/Builder/Process/CreateStudent.php
  src/Gibbon/FileUploader.php
  tests/unit/Data/PasswordPolicyCest.php
Labels: refactoring

#1704 GitHub Actions: make phpstan (level 0) test essential
  .github/workflows/ci.yml
Labels: testing

#1705 Attendance: fix attendance for classes timetabled multiple times on the same day
  CHANGEDB.php
  CHANGELOG.txt
  modules/Attendance/attendance_take_byCourseClass.php
  modules/Attendance/attendance_take_byCourseClassProcess.php
  modules/Planner/planner_view_full.php
  src/Domain/Timetable/TimetableDayDateGateway.php
  src/Forms/Traits/MultipleOptionsTrait.php
Labels: bug
