Repository GibbonEdu/core, pull requests merged in 2024-01, with the labels that each got.

#1771 github: fix issue link to feature request
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug

#1772 gitlab-ci: PHP 8.3 testing update
  .gitlab-ci.yml
Labels: enhancement

#1770 Added Facilities to Fast Finder Search
  CHANGELOG.txt
  indexFindRedirect.php
  index_fastFinder_ajax.php
Labels: enhancement

#1777 Added 'active' column to gibbonSpace table and changed pages to only show active facilities.
  CHANGEDB.php
  CHANGELOG.txt
  index_fastFinder_ajax.php
  modules/School Admin/space_manage.php
  modules/School Admin/space_manage_add.php
  modules/School Admin/space_manage_addProcess.php
  modules/School Admin/space_manage_edit.php
  modules/School Admin/space_manage_editProcess.php
  modules/Timetable/report_viewAvailableSpaces.php
  modules/Timetable/spaceBooking_manage_add.php
  modules/Timetable/tt_space.php
  src/Domain/School/FacilityGateway.php
Labels: enhancement

#1780 [L10n] Update FormFactory.php: "ราชอาณาจักรไทย" -> "ประเทศไทย"
  src/Forms/FormFactory.php
Labels: enhancement

#1781 Updated Format file to remove in-baked styling
  CHANGELOG.txt
  src/Services/Format.php
Labels: css, php

#1775 Updated JQuery and JQuery Migrate Files
  CHANGELOG.txt
  lib/jquery/jquery-migrate.min.js
  lib/jquery/jquery.js
  lib/thickbox/thickbox-compressed.js
Labels: enhancement
