Repository GibbonEdu/core, pull requests merged in 2024-03, with the labels that each got.

#1799 Functions: reformatting functions.php
  functions.php
Labels: enhancement

#1794 Implementing Library Shelves as a UI Upgrade
  CHANGEDB.php
  CHANGELOG.txt
  modules/Library/library_browse.php
  modules/Library/library_manage_catalog.php
  modules/Library/library_manage_shelves.php
  modules/Library/library_manage_shelves_add.php
  modules/Library/library_manage_shelves_addProcess.php
  modules/Library/library_manage_shelves_delete.php
  modules/Library/library_manage_shelves_deleteProcess.php
  modules/Library/library_manage_shelves_edit.php
  modules/Library/library_manage_shelves_editProcess.php
  modules/Library/library_manage_shelves_edit_items_delete.php
  modules/Library/library_manage_shelves_edit_items_deleteProcess.php
  modules/Library/library_searchAjax.php
  modules/Library/library_shelves_editOrderAjax.php
  modules/Library/library_shelves_editProcessBulk.php
  modules/Library/templates/librarySearch.twig.html
  modules/Library/templates/libraryShelves.twig.html
  src/Domain/Library/LibraryGateway.php
  src/Domain/Library/LibraryShelfGateway.php
  src/Domain/Library/LibraryShelfItemGateway.php
Labels: in development, enhancement

#1800 FileUploader & addQuick: Bug fix so that filenames include Chinese cha…
  CHANGELOG.txt
  modules/Planner/resources_addQuick_ajaxProcess.php
  src/Gibbon/FileUploader.php
Labels: bug

#1801 Bug Fix: Fixed the bug of messageWall widget and messageWall messages…
  CHANGELOG.txt
  src/Domain/Messenger/MessengerGateway.php
  src/UI/Components/Sidebar.php
Labels: bug

#1798 Functions: Updated the getSalt() function so that it uses the mt_rand() function
  CHANGELOG.txt
  functions.php
Labels: enhancement

#1806 Messenger- Created a new index to reduce the run time for nested quer…
  CHANGEDB.php
  CHANGELOG.txt
Labels: refactoring
