Repository GibbonEdu/core, pull requests merged in 2024-02, with the labels that each got.

#1787 GitHub Actions: CI to check PHP Notice
  .github/workflows/ci.yml
Labels: testing, enhancement

#1790 GitHub Actions: CI always check server logs
  .github/workflows/ci.yml
Labels: enhancement

#1791 GitHub Actions: update workflow actions for node20 transition
  .github/workflows/ci.yml
Labels: enhancement

#1784 System: refactoring error messages
  modules/Planner/outcomes.php
  modules/Planner/planner.php
  modules/Planner/planner_add.php
  modules/Planner/planner_bump.php
  modules/Planner/planner_delete.php
  modules/Planner/planner_duplicate.php
  modules/Planner/planner_edit.php
  modules/Planner/planner_unitOverview.php
  modules/Planner/planner_view_full.php
  modules/Planner/planner_view_full_post.php
  modules/Planner/planner_view_full_submit_edit.php
  modules/Planner/resources_manage_add.php
  modules/Planner/resources_manage_edit.php
  modules/Planner/units_add.php
  modules/Planner/units_delete.php
  modules/Planner/units_duplicate.php
  modules/Planner/units_edit.php
  modules/Planner/units_edit_copyForward.php
  modules/Rubrics/rubrics.php
  modules/Rubrics/rubrics_add.php
  modules/Rubrics/rubrics_delete.php
  modules/Rubrics/rubrics_duplicate.php
  modules/Rubrics/rubrics_edit.php
  modules/Rubrics/rubrics_edit_editRowsColumns.php
  modules/Staff/staff_manage_edit.php
  modules/Staff/staff_view_details.php
  modules/Students/firstAidRecord_add.php
  modules/Students/student_view_details.php
  modules/Students/student_view_details_notes_edit.php
  modules/Timetable/spaceBooking_manage.php
  modules/Timetable/spaceBooking_manage_add.php
  modules/Timetable/spaceBooking_manage_delete.php
  modules/Timetable/spaceChange_manage.php
  modules/Timetable/spaceChange_manage_add.php
  modules/Timetable/spaceChange_manage_delete.php
  modules/Timetable/tt.php
  modules/Timetable/tt_space.php
  modules/Timetable/tt_space_view.php
  modules/Timetable/tt_view.php
  modules/Tracking/graphing.php
Labels: refactoring

#1792 System: Refactoring code to retrieve object from container
  cli/attendance_dailyIncompleteEmail.php
  cli/attendance_dailyIncompleteEmail_byClass.php
  cli/attendance_weeklySummaryEmail.php
  cli/behaviour_lettersNegative.php
  cli/behaviour_lettersPositive.php
  cli/library_overdueNotification.php
  cli/userAdmin_removeStaleNotifications.php
  modules/Behaviour/behaviour_manage_addMultiProcess.php
  modules/Behaviour/behaviour_manage_addProcess.php
  modules/Data Updater/data_personal_manage_editProcess.php
  modules/Individual Needs/investigations_manage_addProcess.php
  modules/Individual Needs/investigations_manage_editProcess.php
  modules/Individual Needs/investigations_submit_detailProcess.php
  modules/Messenger/src/MessageProcess.php
  modules/Planner/planner_addProcess.php
  modules/Planner/planner_editProcess.php
  modules/Planner/planner_view_full_postProcess.php
  modules/User Admin/user_manage_editProcess.php
Labels: refactoring

#1786 System: Refactoring code and editing error message by adding blank state
  modules/Activities/activities_attendance.php
  modules/Activities/activities_attendance_sheet.php
  modules/Activities/activities_attendance_sheetPrint.php
  modules/Activities/activities_payment.php
  modules/Activities/activities_view.php
  modules/Activities/activities_view_register.php
  modules/Activities/report_activityChoices_byFormGroup.php
  modules/Activities/report_attendance.php
  modules/Activities/report_attendance_print.php
  modules/Admissions/report_graph_studentEnrolment.php
  modules/Attendance/attendance_take_adHoc.php
  modules/Attendance/attendance_take_byCourseClass.php
  modules/Attendance/attendance_take_byFormGroup.php
  modules/Attendance/report_consecutiveAbsences.php
  modules/Attendance/report_courseClassesNotRegistered_byDate.php
  modules/Attendance/report_courseClassesNotRegistered_byDate_print.php
  modules/Attendance/report_formGroupsNotRegistered_byDate.php
  modules/Attendance/report_formGroupsNotRegistered_byDate_print.php
  modules/Attendance/report_graph_byType.php
  modules/Attendance/report_studentHistory.php
  modules/Attendance/report_summary_byDate.php
  modules/Finance/expenseRequest_manage.php
  modules/Finance/invoices_view.php
  modules/Formal Assessment/externalAssessment_manage_details_add.php
  modules/Formal Assessment/externalAssessment_view.php
  modules/Formal Assessment/internalAssessment_manage.php
  modules/Formal Assessment/internalAssessment_view.php
  modules/Individual Needs/iep_view_myChildren.php
  modules/Individual Needs/in_archive.php
  modules/Markbook/markbook_edit.php
  modules/Markbook/markbook_edit_copy.php
  modules/Markbook/markbook_viewExportContents.php
  modules/Markbook/markbook_view_viewMyChildrensClasses.php
  modules/Markbook/weighting_manage.php
  modules/Messenger/messenger_manage_report.php
  modules/Planner/conceptExplorer.php
  modules/Planner/planner.php
  modules/Planner/planner_deadlines.php
  modules/Planner/planner_unitOverview.php
  modules/Planner/scopeAndSequence.php
  modules/Planner/units_dump.php
  modules/Planner/units_public.php
  modules/Planner/units_public_view.php
  modules/Staff/coverage_my.php
  modules/Staff/staff_view_details.php
  modules/Students/report_lettersHome_byFormGroup.php
  modules/Students/report_students_ageGenderSummary.php
  modules/Students/student_view.php
  modules/Students/student_view_details.php
  modules/System Admin/formBuilder_page_design.php
  modules/System Admin/import_history_view.php
  modules/Timetable Admin/courseEnrolment_manage.php
  modules/Timetable Admin/courseEnrolment_manage_byPerson_edit.php
  modules/Timetable Admin/ttDates.php
  modules/Timetable/studentEnrolment_manage.php
  modules/Timetable/tt_master.php
  modules/Timetable/tt_space_view.php
  modules/Timetable/tt_view.php
  modules/Tracking/graphing.php
Labels: refactoring
